### ISSUE TITLE
support redefinition of connection timeout

### ISSUE THREAD

**Issue by plz** [purestorage/rest-client#8]
Considering the rest client relies on [requests](http://docs.python-requests.org/en/master/user/quickstart/#timeouts) it would be good to allow users to redefine the timeout parameter.

**Comment by mksteele** [comment]
Can you elaborate on what you want? Would this be something like a global "timeout" parameter passed into the FlashArray() __init__ function? Or would this be specified per each request?

**Comment by plz** [comment]
I think a global one would be a good start Miranda. Thanks!

**Comment by zolstein** [comment]
We have added the option to pass in a dict of parameters (request_kwargs) that we then pass to the request method. This should satisfy this use-case.
